build.version="3.0"

accounts.message="Welcome to Ajay Bank"
accounts.contactDetails.name="Ajay"
accounts.contactDetails.email="Ajay@gmail.com"
accounts.onCallSupport=-(555)555-1234,-(555)555-1243






