
build.version=10.0

accounts.message=Welcome to Ajay prod Bank
accounts.contactDetails.name=Kumar
accounts.contactDetails.email=kumar@gmail.com
accounts.onCallSupport=(555)555-2222,(555)555-3333


