build.version=2.0

accounts.message=Welcome to Ajay QA Bank
accounts.contactDetails.name=Rayapati
accounts.contactDetails.email=rayapati@gmail.com
accounts.onCallSupport=(555)555-9090,(555)555-0909

